version: 2
jobs:
  build:
    working_directory: ~/marmosad-lambda-experiment

    docker:
      - image: ppshein/apex-docker:latest
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Deploy application
          command: apex deploy --region us-east-1

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

#      - deploy:
#          name: install production dependencies
#          command: |
#            apex deploy --region us-east-1